name: Basic Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r exercises/01-basic-workflow/requirements.txt
          
      - name: Run tests
        run: |
          cd exercises/01-basic-workflow
          pytest test_calculator.py -v --cov=. --cov-report=xml
          
      - name: Print test summary
        run: |
          echo "Tests completed successfully!"
          echo "Branch name: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: exercises/01-basic-workflow/coverage.xml

  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
    
    - name: Check code formatting
      run: |
        cd exercises/01-basic-workflow
        black --check .
        isort --check-only .
    
    - name: Lint with flake8
      run: |
        cd exercises/01-basic-workflow
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --statistics 